DROP TABLE IF EXISTS eventos;
CREATE TABLE eventos(
	id_eventos INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_viagem INTEGER NOT NULL,
    tipo VARCHAR(20) DEFAULT NULL,    
    latitude VARCHAR(10) NOT NULL,
    longitude VARCHAR(10) NOT NULL,
	CONSTRAINT fk_Eventos_Viagem FOREIGN KEY (id_viagem) REFERENCES viagem(id_viagem) ON UPDATE CASCADE ON DELETE CASCADE);