DROP TABLE IF EXISTS utilizador;
CREATE TABLE utilizador(
	id_user INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
	mail VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(20) NOT NULL,
    idade INTEGER DEFAULT NULL CHECK(idade BETWEEN 0 AND 120),
    genero CHAR DEFAULT NULL CHECK(genero IN('M', 'F')),
	contacto INTEGER DEFAULT NULL);

